<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="163" started-at="2017-05-02T02:50:39Z" finished-at="2017-05-02T02:50:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="163" started-at="2017-05-02T02:50:39Z" finished-at="2017-05-02T02:50:39Z">
      <class name="org.lvzr.fast.test.powermock.BactchConvertorTest">
        <test-method status="PASS" signature="before()[pri:0, instance:org.lvzr.fast.test.powermock.BactchConvertorTest@26be92ad]" name="before" is-config="true" duration-ms="5" started-at="2017-05-02T10:50:39Z" finished-at="2017-05-02T10:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="testNormalMock()[pri:0, instance:org.lvzr.fast.test.powermock.BactchConvertorTest@26be92ad]" name="testNormalMock" duration-ms="144" started-at="2017-05-02T10:50:39Z" finished-at="2017-05-02T10:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNormalMock -->
        <test-method status="FAIL" signature="testStaticMock()[pri:0, instance:org.lvzr.fast.test.powermock.BactchConvertorTest@26be92ad]" name="testStaticMock" duration-ms="3" started-at="2017-05-02T10:50:39Z" finished-at="2017-05-02T10:50:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [lvzrName] but found [user_name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [lvzrName] but found [user_name]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at org.lvzr.fast.test.powermock.BactchConvertorTest.testStaticMock(BactchConvertorTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testStaticMock -->
      </class> <!-- org.lvzr.fast.test.powermock.BactchConvertorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
